import { randomUUID } from "node:crypto";
import { mkdir, copyFile } from "node:fs/promises";
import path from "node:path";
import { loadHarness, compileHarness } from "./compiler.js";
import { ArtifactManager } from "./artifacts.js";
import { TraceLogger } from "./trace.js";
import { evaluateGateSpec } from "./gates.js";
import type { RuntimeResult, RuntimeState } from "./state.js";
import type { StageSpec } from "./schema.js";
import { RuntimeError } from "./errors.js";

const candidatePatch = [
  "diff --git a/src/math.ts b/src/math.ts",
  "index 0000000..0000001 100644",
  "--- a/src/math.ts",
  "+++ b/src/math.ts",
  "@@ -1,3 +1,3 @@",
  " export function add(a: number, b: number): number {",
  "-  return a - b;",
  "+  return a + b;",
  " }",
  ""
].join("\n");

async function writeOutputArtifact(
  output: string,
  state: RuntimeState,
  artifacts: ArtifactManager
): Promise<void> {
  if (output === "IssueContract") {
    await artifacts.writeText(
      output,
      [
        "# Issue Contract",
        "",
        "## Problem Summary",
        "",
        "Fix the target repository task described in TASK.md.",
        "",
        "## Acceptance Criteria",
        "",
        "The patch must satisfy the task and pass verification.",
        "",
        "## Non-Goals",
        "",
        "No unrelated refactors.",
        ""
      ].join("\n")
    );
    return;
  }

  if (output === "RepoMap") {
    await artifacts.writeText(
      output,
      [
        "# Repo Map",
        "",
        "## Problem summary",
        "",
        "The target task concerns the repository behavior described in TASK.md.",
        "",
        "## Relevant files",
        "",
        "- src/math.ts",
        "",
        "## Relevant tests",
        "",
        "- test/math.test.ts",
        "",
        "## Suspected root cause",
        "",
        "Implementation does not satisfy expected behavior.",
        "",
        "## Blast-radius risks",
        "",
        "Keep patch minimal.",
        ""
      ].join("\n")
    );
    return;
  }

  if (output === "CandidatePatch") {
    await artifacts.writeText(output, candidatePatch);
    return;
  }

  if (output === "VerifierReport") {
    await artifacts.writeText(
      output,
      [
        "# Verifier Report",
        "",
        "## Patch Summary",
        "",
        "The candidate patch changes add() to return the sum of its inputs.",
        "",
        "## Tests run",
        "",
        "- git apply --check candidate.patch",
        "",
        "## Evidence",
        "",
        "Patch applies cleanly.",
        "",
        "## Verdict",
        "",
        "Verdict: PASS",
        ""
      ].join("\n")
    );
    return;
  }

  if (output === "FinalPatch") {
    await artifacts.writeText(output, await artifacts.readText("CandidatePatch"));
    return;
  }

  if (output === "PRSummary") {
    await artifacts.writeText(
      output,
      [
        "# PR Summary",
        "",
        "## Summary",
        "",
        "Fix add() so it returns a + b.",
        "",
        "## Files changed",
        "",
        "- src/math.ts",
        "",
        "## Tests run",
        "",
        "- git apply --check candidate.patch",
        "",
        "## Verification evidence",
        "",
        "Verifier report returned Verdict: PASS.",
        "",
        "## Residual risk",
        "",
        "Minimal; single-line arithmetic fix.",
        ""
      ].join("\n")
    );
    return;
  }

  await artifacts.writeText(output, `Generated by ${state.currentState}.\n`);
}

async function executeDeterministicStage(
  _stageName: string,
  stage: StageSpec,
  state: RuntimeState,
  artifacts: ArtifactManager
): Promise<string[]> {
  const created: string[] = [];
  for (const output of stage.outputs) {
    await writeOutputArtifact(output, state, artifacts);
    created.push(output);
  }
  return created;
}

async function failRun(
  logger: TraceLogger,
  result: Omit<RuntimeResult, "status">,
  message: string
): Promise<RuntimeResult> {
  await logger.emit("run_failed", { message });
  return {
    ...result,
    status: "FAIL",
    message
  };
}

export async function runHarness(
  harnessPath: string,
  repoPath: string,
  taskPath: string,
  runId?: string
): Promise<RuntimeResult> {
  runId ??= randomUUID();
  const resolvedHarnessPath = path.resolve(harnessPath);
  const resolvedRepoPath = path.resolve(repoPath);
  const resolvedTaskPath = path.resolve(taskPath);
  const compiled = compileHarness(await loadHarness(resolvedHarnessPath));

  const runRoot = path.resolve("runs", runId);
  const stateRoot = path.join(runRoot, "state");
  const artifactRoot = path.join(runRoot, "artifacts");
  const tracePath = path.join(stateRoot, "task_history.jsonl");
  await mkdir(stateRoot, { recursive: true });
  await mkdir(artifactRoot, { recursive: true });
  await copyFile(resolvedTaskPath, path.join(runRoot, "TASK.md"));

  const artifacts = new ArtifactManager(runRoot, compiled.spec);
  const logger = new TraceLogger(tracePath, runId);
  const state: RuntimeState = {
    runId,
    currentState: compiled.startState,
    taskPath: resolvedTaskPath,
    repoPath: resolvedRepoPath,
    harnessPath: resolvedHarnessPath,
    runRoot,
    stateRoot,
    artifactRoot,
    stageHistory: [],
    artifacts: {}
  };

  const resultBase = {
    runId,
    finalState: state.currentState,
    runRoot,
    artifactRoot,
    tracePath
  };

  await logger.emit("run_started", { fromState: state.currentState });

  try {
    while (!compiled.terminalStates.includes(state.currentState)) {
      const stages = compiled.stagesByFromState[state.currentState] ?? [];
      if (stages.length === 0) {
        throw new RuntimeError(`no enabled stage for state: ${state.currentState}`);
      }
      const stageEntry = [...stages].sort((a, b) => a.name.localeCompare(b.name))[0];
      if (!stageEntry) {
        throw new RuntimeError(`no enabled stage for state: ${state.currentState}`);
      }

      await logger.emit("stage_started", {
        stage: stageEntry.name,
        fromState: stageEntry.spec.from,
        toState: stageEntry.spec.to
      });

      const created = await executeDeterministicStage(stageEntry.name, stageEntry.spec, state, artifacts);
      for (const artifact of created) {
        state.artifacts[artifact] = await artifacts.status(artifact);
        await logger.emit("artifact_created", { stage: stageEntry.name, artifact });
      }

      for (const output of stageEntry.spec.outputs) {
        const status = await artifacts.status(output);
        if (!status.exists || (status.sizeBytes ?? 0) === 0) {
          return failRun(
            logger,
            { ...resultBase, finalState: state.currentState },
            `missing required output artifact: ${output}`
          );
        }
      }

      const gateResults = await evaluateGateSpec(stageEntry.spec.gate, state, artifacts);
      for (const gate of gateResults) {
        const payload =
          gate.message === undefined
            ? {
                stage: stageEntry.name,
                gate: gate.gate,
                passed: gate.passed
              }
            : {
                stage: stageEntry.name,
                gate: gate.gate,
                passed: gate.passed,
                message: gate.message
              };
        await logger.emit(gate.passed ? "gate_passed" : "gate_failed", {
          ...payload
        });
      }
      const failedGate = gateResults.find((gate) => !gate.passed);
      if (failedGate) {
        return failRun(
          logger,
          { ...resultBase, finalState: state.currentState },
          `gate failed: ${failedGate.gate}: ${failedGate.message ?? ""}`.trim()
        );
      }

      const previousState = state.currentState;
      state.currentState = stageEntry.spec.to;
      await logger.emit("state_transition", {
        stage: stageEntry.name,
        fromState: previousState,
        toState: state.currentState
      });
      await logger.emit("stage_completed", {
        stage: stageEntry.name,
        fromState: previousState,
        toState: state.currentState
      });
    }

    await logger.emit("run_completed", { toState: state.currentState });
    return {
      ...resultBase,
      status: "PASS",
      finalState: state.currentState
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return failRun(logger, { ...resultBase, finalState: state.currentState }, message);
  }
}
