import type { ArtifactManager } from "./artifacts.js";
import type { RuntimeState } from "./state.js";

export type WorkerInput = {
  stageName: string;
  roleName: string;
  rolePrompt?: string;
  state: RuntimeState;
  declaredInputs: string[];
  declaredOutputs: string[];
};

export type WorkerOutput = {
  createdArtifacts: string[];
  message?: string;
};

export interface WorkerAdapter {
  execute(input: WorkerInput, artifacts: ArtifactManager): Promise<WorkerOutput>;
}

const candidatePatch = [
  "diff --git a/src/math.ts b/src/math.ts",
  "index 0000000..0000001 100644",
  "--- a/src/math.ts",
  "+++ b/src/math.ts",
  "@@ -1,3 +1,3 @@",
  " export function add(a: number, b: number): number {",
  "-  return a - b;",
  "+  return a + b;",
  " }",
  ""
].join("\n");

async function writeDeterministicArtifact(
  output: string,
  state: RuntimeState,
  artifacts: ArtifactManager
): Promise<void> {
  if (output === "IssueContract") {
    await artifacts.writeText(
      output,
      [
        "# Issue Contract",
        "",
        "## Problem Summary",
        "",
        "Fix the target repository task described in TASK.md.",
        "",
        "## Acceptance Criteria",
        "",
        "The patch must satisfy the task and pass verification.",
        "",
        "## Non-Goals",
        "",
        "No unrelated refactors.",
        ""
      ].join("\n")
    );
    return;
  }

  if (output === "RepoMap") {
    await artifacts.writeText(
      output,
      [
        "# Repo Map",
        "",
        "## Problem summary",
        "",
        "The target task concerns the repository behavior described in TASK.md.",
        "",
        "## Relevant files",
        "",
        "- src/math.ts",
        "",
        "## Relevant tests",
        "",
        "- test/math.test.ts",
        "",
        "## Suspected root cause",
        "",
        "Implementation does not satisfy expected behavior.",
        "",
        "## Blast-radius risks",
        "",
        "Keep patch minimal.",
        ""
      ].join("\n")
    );
    return;
  }

  if (output === "CandidatePatch") {
    await artifacts.writeText(output, candidatePatch);
    return;
  }

  if (output === "VerifierReport") {
    await artifacts.writeText(
      output,
      [
        "# Verifier Report",
        "",
        "## Patch Summary",
        "",
        "The candidate patch changes add() to return the sum of its inputs.",
        "",
        "## Tests run",
        "",
        "- git apply --check candidate.patch",
        "",
        "## Evidence",
        "",
        "Patch applies cleanly.",
        "",
        "## Verdict",
        "",
        "Verdict: PASS",
        ""
      ].join("\n")
    );
    return;
  }

  if (output === "FinalPatch") {
    await artifacts.writeText(output, await artifacts.readText("CandidatePatch"));
    return;
  }

  if (output === "PRSummary") {
    await artifacts.writeText(
      output,
      [
        "# PR Summary",
        "",
        "## Summary",
        "",
        "Fix add() so it returns a + b.",
        "",
        "## Files changed",
        "",
        "- src/math.ts",
        "",
        "## Tests run",
        "",
        "- git apply --check candidate.patch",
        "",
        "## Verification evidence",
        "",
        "Verifier report returned Verdict: PASS.",
        "",
        "## Residual risk",
        "",
        "Minimal; single-line arithmetic fix.",
        ""
      ].join("\n")
    );
    return;
  }

  await artifacts.writeText(output, `Generated by ${state.currentState}.\n`);
}

export class DeterministicWorkerAdapter implements WorkerAdapter {
  async execute(input: WorkerInput, artifacts: ArtifactManager): Promise<WorkerOutput> {
    const createdArtifacts: string[] = [];
    for (const output of input.declaredOutputs) {
      await writeDeterministicArtifact(output, input.state, artifacts);
      createdArtifacts.push(output);
    }
    return { createdArtifacts };
  }
}
